/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCasesRouteImport } from './routes/app.cases'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppCasesIndexRouteImport } from './routes/app.cases.index'
import { Route as AppCasesCaseIdRouteImport } from './routes/app.cases.$caseId'
import { Route as AppCasesCaseIdTasksRouteImport } from './routes/app.cases.$caseId.tasks'
import { Route as AppCasesCaseIdEventsRouteImport } from './routes/app.cases.$caseId.events'
import { Route as AppCasesCaseIdDocumentsRouteImport } from './routes/app.cases.$caseId.documents'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppCasesCaseIdTasksRoute = AppCasesCaseIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppCasesCaseIdRoute,
} as any)
const AppCasesCaseIdEventsRoute = AppCasesCaseIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppCasesCaseIdRoute,
} as any)
const AppCasesCaseIdDocumentsRoute = AppCasesCaseIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppCasesCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/cases': typeof AppCasesRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/cases/$caseId': typeof AppCasesCaseIdRouteWithChildren
  '/app/cases/': typeof AppCasesIndexRoute
  '/app/cases/$caseId/documents': typeof AppCasesCaseIdDocumentsRoute
  '/app/cases/$caseId/events': typeof AppCasesCaseIdEventsRoute
  '/app/cases/$caseId/tasks': typeof AppCasesCaseIdTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/cases/$caseId': typeof AppCasesCaseIdRouteWithChildren
  '/app/cases': typeof AppCasesIndexRoute
  '/app/cases/$caseId/documents': typeof AppCasesCaseIdDocumentsRoute
  '/app/cases/$caseId/events': typeof AppCasesCaseIdEventsRoute
  '/app/cases/$caseId/tasks': typeof AppCasesCaseIdTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/cases': typeof AppCasesRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/cases/$caseId': typeof AppCasesCaseIdRouteWithChildren
  '/app/cases/': typeof AppCasesIndexRoute
  '/app/cases/$caseId/documents': typeof AppCasesCaseIdDocumentsRoute
  '/app/cases/$caseId/events': typeof AppCasesCaseIdEventsRoute
  '/app/cases/$caseId/tasks': typeof AppCasesCaseIdTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/ai'
    | '/app/analytics'
    | '/app/billing'
    | '/app/calendar'
    | '/app/cases'
    | '/app/clients'
    | '/app/documents'
    | '/app/messages'
    | '/app/settings'
    | '/app/users'
    | '/app/'
    | '/app/cases/$caseId'
    | '/app/cases/'
    | '/app/cases/$caseId/documents'
    | '/app/cases/$caseId/events'
    | '/app/cases/$caseId/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/ai'
    | '/app/analytics'
    | '/app/billing'
    | '/app/calendar'
    | '/app/clients'
    | '/app/documents'
    | '/app/messages'
    | '/app/settings'
    | '/app/users'
    | '/app'
    | '/app/cases/$caseId'
    | '/app/cases'
    | '/app/cases/$caseId/documents'
    | '/app/cases/$caseId/events'
    | '/app/cases/$caseId/tasks'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/ai'
    | '/app/analytics'
    | '/app/billing'
    | '/app/calendar'
    | '/app/cases'
    | '/app/clients'
    | '/app/documents'
    | '/app/messages'
    | '/app/settings'
    | '/app/users'
    | '/app/'
    | '/app/cases/$caseId'
    | '/app/cases/'
    | '/app/cases/$caseId/documents'
    | '/app/cases/$caseId/events'
    | '/app/cases/$caseId/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases': {
      id: '/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases/': {
      id: '/app/cases/'
      path: '/'
      fullPath: '/app/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/app/cases/$caseId': {
      id: '/app/cases/$caseId'
      path: '/$caseId'
      fullPath: '/app/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/app/cases/$caseId/tasks': {
      id: '/app/cases/$caseId/tasks'
      path: '/tasks'
      fullPath: '/app/cases/$caseId/tasks'
      preLoaderRoute: typeof AppCasesCaseIdTasksRouteImport
      parentRoute: typeof AppCasesCaseIdRoute
    }
    '/app/cases/$caseId/events': {
      id: '/app/cases/$caseId/events'
      path: '/events'
      fullPath: '/app/cases/$caseId/events'
      preLoaderRoute: typeof AppCasesCaseIdEventsRouteImport
      parentRoute: typeof AppCasesCaseIdRoute
    }
    '/app/cases/$caseId/documents': {
      id: '/app/cases/$caseId/documents'
      path: '/documents'
      fullPath: '/app/cases/$caseId/documents'
      preLoaderRoute: typeof AppCasesCaseIdDocumentsRouteImport
      parentRoute: typeof AppCasesCaseIdRoute
    }
  }
}

interface AppCasesCaseIdRouteChildren {
  AppCasesCaseIdDocumentsRoute: typeof AppCasesCaseIdDocumentsRoute
  AppCasesCaseIdEventsRoute: typeof AppCasesCaseIdEventsRoute
  AppCasesCaseIdTasksRoute: typeof AppCasesCaseIdTasksRoute
}

const AppCasesCaseIdRouteChildren: AppCasesCaseIdRouteChildren = {
  AppCasesCaseIdDocumentsRoute: AppCasesCaseIdDocumentsRoute,
  AppCasesCaseIdEventsRoute: AppCasesCaseIdEventsRoute,
  AppCasesCaseIdTasksRoute: AppCasesCaseIdTasksRoute,
}

const AppCasesCaseIdRouteWithChildren = AppCasesCaseIdRoute._addFileChildren(
  AppCasesCaseIdRouteChildren,
)

interface AppCasesRouteChildren {
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRouteWithChildren
  AppCasesIndexRoute: typeof AppCasesIndexRoute
}

const AppCasesRouteChildren: AppCasesRouteChildren = {
  AppCasesCaseIdRoute: AppCasesCaseIdRouteWithChildren,
  AppCasesIndexRoute: AppCasesIndexRoute,
}

const AppCasesRouteWithChildren = AppCasesRoute._addFileChildren(
  AppCasesRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCasesRoute: typeof AppCasesRouteWithChildren
  AppClientsRoute: typeof AppClientsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCasesRoute: AppCasesRouteWithChildren,
  AppClientsRoute: AppClientsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
